---
- name: "Install ranger using APT"
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - ranger

- name: "Symlink ranger dotfiles"
  shell: stow -d ~/.dotfiles/home -t ~/ {{ item }}
  with_items:
    - ranger
