---
- name: Install libraries using APT
  sudo: true
  apt: name={{ item }} state=latest
  with_items:
    - git
    - stow
    - zsh
    - emacs
    - ranger
    - bc

- name: Change default shell to fish
  sudo: true
  user: shell='/usr/bin/zsh' name={{ ansible_ssh_user }}
