---
- name: Install htop using APT
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - htop

- name: Symlink htop dotfiles
  shell: stow -d ~/.dotfiles/home -t ~/ {{ item }}
  with_items:
    - htop
