---
- name: Install irssi using APT
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - irssi

- name: Symlink irssi dotfiles
  shell: stow -d ~/.dotfiles/home -t ~/ {{ item }}
  with_items:
    - irssi
